packages: ['@downforce/*', '@downforce/*/tests']

allowBuilds:
    'esbuild': true
    'nx': false

managePackageManagerVersions: true
packageManagerStrictVersion: true

optimisticRepeatInstall: true

autoInstallPeers: true
strictDepBuilds: true
strictPeerDependencies: true

hoist: false
hoistWorkspacePackages: false
hoistPattern: []
publicHoistPattern: []

linkWorkspacePackages: deep
preferWorkspacePackages: true
