packages: ['@downforce/*', '@downforce/*/tests']

onlyBuiltDependencies: ['esbuild']
ignoredBuiltDependencies: ['nx']

managePackageManagerVersions: true
packageManagerStrictVersion: true

optimisticRepeatInstall: true
verifyDepsBeforeRun: install

autoInstallPeers: true
strictDepBuilds: true
strictPeerDependencies: true

hoist: false
hoistWorkspacePackages: false
hoistPattern: []
publicHoistPattern: []

linkWorkspacePackages: deep
preferWorkspacePackages: true
