[tasks.init]
depends=[
    '//:init',
    '//@downforce/tsconfig:build',
]
run='./bin/init.sh'

[tasks.build]
depends=[':init']
run='./bin/build.sh'

[tasks.test]
depends=[':build']
run='./bin/test.sh'

[tasks.clean]
run='./bin/clean.sh'
